# Generated by Django 3.0.2 on 2020-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
