# Generated by Django 3.0.2 on 2020-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200530_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsemodel',
            name='device_serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
