# Generated by Django 3.0.2 on 2020-01-26 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.UserProfile')),
                ('specialty', models.CharField(choices=[('Anesthesiologists\u200e', 'Anesthesiologists'), ('Cardiologists\u200e', 'Cardiologists\u200e'), ('Coroners\u200e', 'Coroners\u200e'), ('Dentists\u200e', 'Dentists\u200e'), ('Dermatologists\u200e', 'Dermatologists\u200e'), ('Diabetologists\u200e', 'Diabetologists\u200e'), ('Emergencyphysicians\u200e', 'Emergencyphysicians\u200e'), ('Endocrinologists\u200e', 'Endocrinologists\u200e'), ('Euthanasia', 'Euthanasia'), ('Gastroenterologists\u200e', 'Gastroenterologists\u200e'), ('Generalpractitioners\u200e', 'Generalpractitioners\u200e'), ('Gynaecologists\u200e', 'Gynaecologists\u200e'), ('Hematologists\u200e', 'Hematologists\u200e'), ('Immunologists\u200e', 'Immunologists\u200e'), ('Neurologists\u200e', 'Neurologists\u200e'), ('Neurosurgeons\u200e', 'Neurosurgeons\u200e'), ('Pathologists\u200e', 'Pathologists\u200e')], max_length=30)),
            ],
        ),
    ]
